const SECRET_KEY  =  "JEKNJ83uim"
const JWT_EXPIRATION = 10800 // 3 часа
const JWT_REFRESH_EXPIRATION = 21600 // 6 часов

const JWT_FORGOT_EXPIRATION = 10800 // 10 мин
const SECRET_KEY_FORGOT  =  "FJlkdscvPJv4"

export { SECRET_KEY, JWT_EXPIRATION, JWT_REFRESH_EXPIRATION , JWT_FORGOT_EXPIRATION, SECRET_KEY_FORGOT}; 




